version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cybertek
    volumes:
      - database-data:/var/lib/postgresql/data/  

  jd-ticketing:
    image: jd-ticketing
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db    
volumes:
  database-data: {}